import { TimerIcon } from "lucide-react"
import { builder } from "./builder"
import type { Example } from "./examples"
import { partKey, type PlacedObject, type Schematic } from "./types"

type Pin = [PlacedObject, string]
type Cell = [number, number]

export type MetronomeBench = {
  doc: Schematic
  parts: { u1: PlacedObject; u2: PlacedObject; u3: PlacedObject; u4: PlacedObject; vr1: PlacedObject; vr2: PlacedObject; vr3: PlacedObject; leds: PlacedObject[]; sw: PlacedObject; bat: PlacedObject; buzzer: PlacedObject }
}

export function buildMetronome(grid: number, opts: { tempo?: string; pitch?: string; volume?: string } = {}): MetronomeBench {
  const { doc, place, wire } = builder(grid)
  const vert = (def: string, x: number, y: number, props: Record<string, string> = {}) => place(def, x, y, props, 90)
  const up = (def: string, x: number, y: number, props: Record<string, string> = {}) => place(def, x, y, props, 270)
  const flip = (obj: PlacedObject) => Object.assign(obj, { mirror: true })
  const back = (def: string, x: number, y: number, props: Record<string, string> = {}) => place(def, x, y, props, 180)
  const node = (x: number, y: number) => place("junction", x - 1, y - 1)
  const gnd = (x: number, y: number): Pin => [place("ground", x - 1, y), "GND"]
  const j = (n: PlacedObject): Pin => [n, "J"]
  const join = (...pins: Pin[]) => {
    for (let k = 1; k < pins.length; k++) wire(pins[k - 1][0], pins[k - 1][1], pins[k][0], pins[k][1])
  }
  const via = (a: Pin, b: Pin, ...bends: Cell[]) => wire(a[0], a[1], b[0], b[1], bends)
  const rail = (y: number, xs: number[]) => {
    const nodes = new Map(xs.map((x) => [x, node(x, y)]))
    join(...[...nodes.values()].map(j))
    return (x: number) => j(nodes.get(x)!)
  }
  const R = (x: number, y: number, value: string) => vert("resistor", x, y, { value })
  const C = (x: number, y: number, value: string) => vert("capacitor", x, y, { value })
  const E = (x: number, y: number, value: string) => vert("capacitor-polarized", x, y, { value, vmax: "16 V" })
  const diode = { value: "1N4148" }
  const bc547 = (ref: string) => ({ value: "BC547", ref })

  const top = rail(0, [-1, 2, 6, 13, 30, 34, 38, 48, 64, 71])
  const clear = rail(34, [-1, 4, 12])
  const mid = rail(56, [-1, 44, 48, 51, 54, 58, 66, 80])
  const low = rail(90, [-1, 10, 27, 32, 38, 58])
  join(top(-1), clear(-1), mid(-1), low(-1))

  const sw = vert("switch", 1, 3, { ref: "SW1" })
  const bat = place("battery", 1, 10, { chem: "alkaline", cells: "3", capacity: "2.5 Ah" })
  const bulk = E(5, 3, "100 µF")
  doc.parts[partKey(sw.id, "SW")] = { on: true }
  join(top(2), [sw, "1"])
  join([sw, "2"], [bat, "+"])
  join([bat, "-"], gnd(2, 17))
  join(top(6), [bulk, "1"])
  join([bulk, "2"], gnd(6, 10))

  const u1 = place("ne555", 23, 7, { ref: "U1" })
  const r1 = R(12, 1, "1 kΩ")
  const r2 = R(12, 11, "4.7 kΩ")
  const vr1 = vert("potentiometer", 12, 17, { value: "10 kΩ", ref: "VR1", pos: opts.tempo ?? "0.5" })
  const c1 = E(12, 23, "47 µF")
  const ctrl1 = C(29, 18, "10 nF")
  const dec1 = C(33, 2, "100 nF")
  const tempoPull = R(37, 4, "1 kΩ")
  const dis1 = node(13, 10)
  const wiper1 = node(13, 16)
  const tim1 = node(13, 22)
  const trig1 = node(22, 14)
  const tempo = node(38, 12)
  const tempoDrop = node(36, 12)
  join(top(13), [r1, "1"])
  join([r1, "2"], j(dis1), [r2, "1"])
  join(j(dis1), [u1, "DIS"])
  join([r2, "2"], j(wiper1), [vr1, "1"])
  via([vr1, "W"], j(wiper1), [15, 16])
  join([vr1, "2"], j(tim1), [c1, "1"])
  join([c1, "2"], gnd(13, 30))
  join(j(tim1), j(trig1))
  join([u1, "THRES"], j(trig1))
  join(j(trig1), [u1, "TRIG"])
  join(top(30), [u1, "VCC"])
  join([u1, "VCC"], [u1, "RESET"])
  join([u1, "GND"], gnd(27, 19))
  join([u1, "CTRL"], [ctrl1, "1"])
  join([ctrl1, "2"], gnd(30, 25))
  join(top(34), [dec1, "1"])
  join([dec1, "2"], gnd(34, 8))
  join(top(38), [tempoPull, "1"])
  join([tempoPull, "2"], j(tempo))
  join([u1, "OUT"], j(tempoDrop), j(tempo))

  const clkBase = R(41, 14, "10 kΩ")
  const q1 = place("npn", 45, 17, bc547("Q1"))
  const clkPull = R(47, 3, "10 kΩ")
  const tapClock = node(42, 12)
  const latch = node(48, 15)
  join(j(tempo), j(tapClock))
  join(j(tapClock), [clkBase, "1"])
  join([clkBase, "2"], [q1, "B"])
  join([q1, "E"], gnd(48, 24))
  join(top(48), [clkPull, "1"])
  join([clkPull, "2"], j(latch), [q1, "C"])

  const u4 = place("hc595", 60, 8, { ref: "U4" })
  const dec4 = C(70, 1, "100 nF")
  join(j(tapClock), [u4, "SRCLK"])
  join(j(latch), [u4, "RCLK"])
  join(top(64), [u4, "VCC"])
  join([u4, "GND"], gnd(64, 24))
  join([u4, "OE"], gnd(59, 19))
  join(top(71), [dec4, "1"])
  join([dec4, "2"], gnd(71, 7))

  const outputs = ["QA", "QB", "QC", "QD"] as const
  const rows = [10, 14, 18, 22]
  const fanTurns = [0, 72, 71, 70]
  const tapX = [79, 78, 77, 76]
  const diodeX = [89, 86, 83, 80]
  const stairY = [26, 27, 28, 29]
  const taps = outputs.map((_, k) => node(tapX[k], rows[k]))
  const ret = rows.map((y) => node(98, y))
  const any = diodeX.map((x) => node(x, 37))
  const feedback = node(76, 25)
  join(j(taps[3]), j(feedback))
  const leds = outputs.map((q, k) => {
    const y = rows[k]
    const r = place("resistor", 82, y - 1, { value: "330 Ω" })
    const led = place("led", 89, y - 1, { value: "red", ref: `LED${k + 1}` })
    const d = vert("diode", diodeX[k] - 1, 31, diode)
    if (k === 0) join([u4, q], j(taps[k]))
    else via([u4, q], j(taps[k]), [fanTurns[k], 10 + k], [fanTurns[k], y])
    join(j(taps[k]), [r, "1"])
    join([r, "2"], [led, "1"])
    join([led, "2"], j(ret[k]))
    via(k === 3 ? j(feedback) : j(taps[k]), [d, "1"], [tapX[k], stairY[k]], [diodeX[k], stairY[k]])
    join([d, "2"], j(any[k]))
    return led
  })
  join(...ret.map(j))

  const q4 = flip(place("npn", 97, 24, bc547("Q4")))
  const ledGate = R(102, 28, "4.7 kΩ")
  const ledGateDown = R(105, 28, "100 kΩ")
  const gate4 = node(103, 26)
  join(j(ret[3]), [q4, "C"])
  join([q4, "E"], gnd(98, 31))
  join([q4, "B"], j(gate4), [ledGate, "1"])
  via(j(gate4), [ledGateDown, "1"], [106, 26])
  join([ledGateDown, "2"], gnd(106, 35))

  const anyMid = node(87, 37)
  const anyRight = node(92, 37)
  join(j(any[3]), j(any[2]), j(any[1]), j(anyMid), j(any[0]), j(anyRight))
  const zeroBase = R(86, 38, "10 kΩ")
  const q3 = flip(place("npn", 82, 43, bc547("Q3")))
  const anyDown = R(91, 39, "100 kΩ")
  const zeroPull = R(79, 42, "4.7 kΩ")
  const zero = node(83, 40)
  const zeroTap = node(80, 40)
  const seedTap = node(77, 40)
  join(j(anyMid), [zeroBase, "1"])
  join([zeroBase, "2"], [q3, "B"])
  join([q3, "E"], gnd(83, 50))
  join(j(zero), [q3, "C"])
  join(j(anyRight), [anyDown, "1"])
  join([anyDown, "2"], gnd(92, 46))
  join(j(zero), j(zeroTap), j(seedTap))
  join(j(zeroTap), [zeroPull, "1"])
  join([zeroPull, "2"], mid(80))

  const serInit = back("diode", 71, 39, diode)
  const serFeedback = vert("diode", 68, 27, diode)
  const serDown = R(68, 42, "100 kΩ")
  const ser = node(69, 40)
  join(j(seedTap), [serInit, "1"])
  join([serInit, "2"], j(ser))
  via(j(feedback), [serFeedback, "1"], [69, 25])
  join([serFeedback, "2"], j(ser))
  join(j(ser), [serDown, "1"])
  join([serDown, "2"], gnd(69, 49))
  via(j(ser), [u4, "SER"], [56, 40], [56, 10])

  const cInit = E(3, 36, "22 µF")
  const initBase = R(3, 42, "4.7 kΩ")
  const initDown = R(3, 50, "47 kΩ")
  const dInit = up("diode", 6, 50, diode)
  const q2 = place("npn", 9, 46, bc547("Q2"))
  const clrPull = R(11, 36, "10 kΩ")
  const ib = node(4, 48)
  const ibClamp = node(7, 48)
  const clr = node(12, 43)
  join(clear(4), [cInit, "1"])
  join([cInit, "2"], [initBase, "1"])
  join([initBase, "2"], j(ib), [initDown, "1"])
  join([initDown, "2"], gnd(4, 57))
  join(j(ib), j(ibClamp), [q2, "B"])
  join(j(ibClamp), [dInit, "2"])
  join([dInit, "1"], gnd(7, 57))
  join([q2, "E"], gnd(12, 53))
  join(clear(12), [clrPull, "1"])
  join([clrPull, "2"], j(clr), [q2, "C"])
  via(j(clr), [u4, "SRCLR"], [15, 43], [15, 33], [57, 33], [57, 13])

  const cTrig = place("capacitor", 38, 69, { value: "100 nF" })
  const trigSeries = place("resistor", 43, 69, { value: "1 kΩ" })
  const trigUp = R(47, 62, "10 kΩ")
  const dHigh = up("diode", 50, 62, diode)
  const trigDown = R(47, 72, "22 kΩ")
  const dLow = up("diode", 50, 72, diode)
  const pt = node(48, 70)
  const ptClamp = node(51, 70)
  via(j(tempoDrop), [cTrig, "1"], [36, 70])
  join([cTrig, "2"], [trigSeries, "1"])
  join([trigSeries, "2"], j(pt), j(ptClamp))
  join(mid(48), [trigUp, "1"])
  join([trigUp, "2"], j(pt), [trigDown, "1"])
  join([trigDown, "2"], gnd(48, 79))
  join(mid(51), [dHigh, "2"])
  join([dHigh, "1"], j(ptClamp), [dLow, "2"])
  join([dLow, "1"], gnd(51, 79))

  const u2 = place("ne555", 59, 63, { ref: "U2" })
  const rPulse = R(53, 58, "10 kΩ")
  const cPulse = E(53, 72, "4.7 µF")
  const enPull = R(57, 57, "2.2 kΩ")
  const ctrl2 = C(65, 74, "10 nF")
  const dec2 = C(43, 58, "100 nF")
  const ptim = node(54, 66)
  const reset2 = node(63, 62)
  const pulse = node(74, 68)
  join(j(ptClamp), [u2, "TRIG"])
  join(mid(54), [rPulse, "1"])
  join([rPulse, "2"], j(ptim), [cPulse, "1"])
  join(j(ptim), [u2, "DIS"])
  join([u2, "DIS"], [u2, "THRES"])
  join([cPulse, "2"], gnd(54, 79))
  join(mid(66), [u2, "VCC"])
  join(mid(58), [enPull, "1"])
  join([enPull, "2"], j(reset2))
  join(j(reset2), [u2, "RESET"])
  join([u2, "GND"], gnd(63, 75))
  join([u2, "CTRL"], [ctrl2, "1"])
  join([ctrl2, "2"], gnd(66, 81))
  join(mid(44), [dec2, "1"])
  join([dec2, "2"], gnd(44, 65))
  join([u2, "OUT"], j(pulse))
  via(j(pulse), [ledGate, "2"], [103, 68])

  const q6Base = R(76, 42, "47 kΩ")
  const q6 = flip(place("npn", 72, 58, bc547("Q6")))
  join(j(seedTap), [q6Base, "1"])
  join([q6Base, "2"], [q6, "B"])
  join([q6, "E"], gnd(73, 65))
  via([q6, "C"], j(reset2), [73, 57], [63, 57])

  const u3 = place("ne555", 20, 97, { ref: "U3" })
  const toneA = R(9, 91, "1 kΩ")
  const toneB = R(9, 101, "1 kΩ")
  const vr2 = vert("potentiometer", 9, 107, { value: "10 kΩ", ref: "VR2", pos: opts.pitch ?? "0.5" })
  const cTone = C(9, 113, "100 nF")
  const tonePull = R(31, 94, "1 kΩ")
  const ctrl3 = C(26, 108, "10 nF")
  const dec3 = C(37, 94, "100 nF")
  const tdis = node(10, 100)
  const tWiper = node(10, 106)
  const ttim = node(10, 112)
  const ttrig = node(19, 104)
  const tone = node(32, 102)
  join(low(10), [toneA, "1"])
  join([toneA, "2"], j(tdis), [toneB, "1"])
  join(j(tdis), [u3, "DIS"])
  join([toneB, "2"], j(tWiper), [vr2, "1"])
  via([vr2, "W"], j(tWiper), [12, 106])
  join([vr2, "2"], j(ttim), [cTone, "1"])
  join([cTone, "2"], gnd(10, 120))
  join(j(ttim), j(ttrig))
  join([u3, "THRES"], j(ttrig))
  join(j(ttrig), [u3, "TRIG"])
  join(low(27), [u3, "VCC"])
  const reset3 = node(24, 95)
  via(j(pulse), j(reset3), [74, 88], [24, 88])
  join(j(reset3), [u3, "RESET"])
  join([u3, "GND"], gnd(24, 109))
  join([u3, "CTRL"], [ctrl3, "1"])
  join([ctrl3, "2"], gnd(27, 115))
  join(low(32), [tonePull, "1"])
  join([tonePull, "2"], j(tone))
  join([u3, "OUT"], j(tone))
  join(low(38), [dec3, "1"])
  join([dec3, "2"], gnd(38, 99))

  const vr3 = vert("potentiometer", 41, 105, { value: "10 kΩ", ref: "VR3", pos: opts.volume ?? "0.8" })
  const rGate = place("resistor", 47, 106, { value: "1 kΩ" })
  const gateDown = R(52, 109, "100 kΩ")
  const q5 = place("nmos", 55, 105, { value: "2N7000", ref: "Q5", vth: "2.1 V", rdson: "1.8 Ω", idmax: "200 mA", vdsmax: "60 V", pmax: "400 mW" })
  const limit = R(57, 93, "100 Ω")
  const buzzer = vert("resistor", 57, 99, { value: "41.5 Ω", power: "0.5", ref: "BZ1" })
  const dBuzz = up("diode", 60, 99, diode)
  const gate = node(53, 107)
  const pos = node(58, 98)
  const neg = node(58, 104)
  const posClamp = node(61, 98)
  const negClamp = node(61, 104)
  via(j(tone), [vr3, "1"], [42, 102])
  join([vr3, "2"], gnd(42, 112))
  join([vr3, "W"], [rGate, "1"])
  join([rGate, "2"], j(gate), [q5, "G"])
  join(j(gate), [gateDown, "1"])
  join([gateDown, "2"], gnd(53, 116))
  join([q5, "S"], gnd(58, 112))
  join(low(58), [limit, "1"])
  join([limit, "2"], j(pos), [buzzer, "1"])
  join([buzzer, "2"], j(neg), [q5, "D"])
  join(j(pos), j(posClamp), [dBuzz, "2"])
  join([dBuzz, "1"], j(negClamp), j(neg))

  return { doc, parts: { u1, u2, u3, u4, vr1, vr2, vr3, leds, sw, bat, buzzer } }
}

export const metronome: Example = {
  id: "metronome",
  name: "Metronome: three NE555s and a 74HC595",
  description:
    "U1 beats 60–180 times a minute (VR1); each beat clocks the 74HC595 ring LED1 → LED4, fires U2's 52 ms pulse and lets U3 sound VR2's pitch through Q5. Q2 clears the register at power-on, Q3 seeds the first step. BZ1 is a 41.5 Ω stand-in for the passive buzzer.",
  icon: TimerIcon,
  build: (grid) => buildMetronome(grid).doc,
}
