name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ChernihivPolytechnicNationalUniversity/shared-actions/docker-build-push@main
        with:
          context: .
          push: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
