name: Prerelease

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  prerelease:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    uses: ChernihivPolytechnicNationalUniversity/shared-actions/.github/workflows/gitops-prerelease.yml@main
    with:
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
