name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    uses: ChernihivPolytechnicNationalUniversity/shared-actions/.github/workflows/gitops-release.yml@main
    with:
      context: .
      images: |
        Dockerfile
        api=backend/api/Dockerfile
        worker=backend/worker/Dockerfile
      image-source: build
    secrets: inherit
